name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 03 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/zhangjiang' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.yandex.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: zhangjiang Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: ysy989833@gmail.com,1403260048@qq.com,all@huohua.ml,all@haobing.ml
          from: Happy Github
          content_type: text/html
